base = "CTGTACCAGTCTCTTCCACTCTGAAACGATACGCTATGATGCGATTGACATTTGCGTCTCGCACGCCATTGAGCTGTCATCTTGTCAGTATCTAATGGCGTACCGATTTCTCCATAATTCGAACCTTCAGCGGGATTAGAAGCGTTTCCTTCGGGATCTTCGTTCACTGGTTCCTGACTGATAAGCTTGTGATATAGAGTACGATTGTTCTCAAAGCGCATCACTCTTGTGCTAATTTTCCACGCGATTTTCTTTGTTTACGGGTCACAGCCGGCATGGGCGTTTAGCCACGGAAACATCAGCAGTCGCCTCAGTAACTGGAGGGACGTCTGCACCGAGGACCATCGACGCAAACCTGGGTTCACCTTTACCAAGGGAAAGAGCTACTTCCGCATGTTCTTCAAGTCCAGGCAGCATCGCATTGCAGTGGACATATCCTTGACGCACCCCAGCGTTTCCCCAATCATGGTGACGGACCCGCGGATAAGCTCGGTAATCGGTCCTGAAGGATTTTTATCGCTGCTGGTTGTCATTCTCATGGGCATATCGATGTCTTACGGTCAAAAGCATGGCAGAACGAGACAAGTTAGCGGGATTAGCCAGTCTTGAAATGGAGGTATAGGTTAGCATCTGCTTTCCGGTCATTTAGCATCTACTTTCCAGTGCGCTCTGATTTTGACTTAAAGCGCCCGATCAGGAGCTTCCGGCGATGCTTTGGCCGCAAGGCATACGACGCACATTCGCTTGGCTAGCCACTGGTAGGCATTTACTATGAGTTACGCCACCTCATCGGTAGTTACGACGC"

complement = []
for i in base:
    if(i == "A"):
        complement.append("T")
    elif(i == "T"):
        complement.append("A")
    elif(i == "G"):
        complement.append("C")
    elif(i == "C"):
        complement.append("G")

complement_string = ''.join(reversed(complement))
print complement_string


