dna_string = "ATTCCAGGATGCGATAATAGTGGAGCTCTAGGCGAGCTCCGGGAGGTAAGTAGGTTGGTCAGCGCGGCCCAAGAACTTGCATCCCCGTGAATTAAATGCCGACAGGTAGATGTGCTCTTGAATGCTTTGTGTTGAACGGTGGGCTGCGCGTTTTATGCTAGTTTGCCCCAATTCGTTGTGCGAAGGTGGTTCAACAGAAGAGCTTGTCGCTGTTTAAAGTTACAGTGATCTCAGCTTTACGTTCTGGAGTGCCTAAGAGTTATAACACCGCTTACGATGGAGTCGTTAAATCTGGAAGTAACAAATGAAGCGCTGGGAACAAAGCACCCACACCACAGCGGGCTAGGAGACAGCACAGGAGCTAAGGCTTGCGAACTACCTAGTGTCGAAGCGAGCGACACTCTAATGTCTCAGCGAGGAGCGCCAATCCTGCGATGAAATTTACCGGAGTCTGTTTAGCCTGTAATCAAAACCACAAACCGGCAACTAGGAAGAAACGCCATCAAGCGGGATGCGGGCTGTCAGCAGTTACGAACTGCTCTAAGAAGGTGTCGACATGCGCAGTTAAGCAAGCATTGCAAGTAACTTCGAGGTCTGAGTTATGTTGCACCAGATAGAAACAGGATGCTATTTCTGATCGTTGAAAGCATTCGCGCTCTGCACCATTTCTCCTATAGATTTAATTCGCCCTGTGACAAGCGATGAGTCTCCGGCTTGGCTAAGTAGCGTCCTAATCGCTAAACGAATTGATCACCCCCTATATTGTTCTGACGTTAACGGGGTGTTCGATATCCAGCCCGTGGCGTTACGCGGCAACCCGCGGTCGTTGAATGCGCCGAAAGGGGACGTAGTTAAAAATTTTGCGGCCGAATGAATAGTGTCTGCGTCCGC"

A = C = T = G = 0 
for i in dna_string: 
    if(i == "A"):
        A += 1
    if(i == "C"):
        C += 1
    if(i == "T"):
        T += 1
    if(i == "G"):
        G += 1
        
print A, C, G, T