dna_string = "GTTAATTATGGTAGAACAATAAGGAAACATGTCACTTCGACGTCCTCATACAAAGGATGTCGTTCCGCGCATACGGTCAGGACTATAGAGTAACTATGTCCTCGTTACTTCCTATGTACCTAGCGTGCGCATTTGGCCATGAGCTCAGGTACATTGTATGATGTCCTTCCACAGAGCTATCGCACGTGGTAAGAATCGTAGAGGCCTACGTTCTTGGGGTCGGGCGTGCATTCGAGCAATCATCTTAATGGTCGAACAACTTCGAGATAGGATATCGTGCTCCATGAAACAAGAGCGTCGTACCGCGTGGACCCCGGACCGACATGTCTTGATGCGGCGGTAAGTCCACCATGATATGCGGGGTTCCGGACCCTGGCCGGTTAAATAATTAGTCTGCCCTTCCTTTGCACCGATCCGGAGGAACTGATTGCTACTAACTACCAGTACTAAAGAGGCTAACTGTTTATCACGTAAGATGGATGGGGGAGTCTTCCACTCGCCACCCTCCAGGCAACAGCTGTGTCTCAATGCACGTTCATTGACGGCGGCACCACAACTCGTACCCGCTGCACAACGAGATGATGTCTATATGCCCGGGGCTGAGAGACGCTCAGTCAATCTCACGCGTATGGTAATTATTGCTCCTCCTACTTATCCACGGTCGAAGGAAATCACCCTTCGCTATAGTTCTTCAAATCAACTATGGTTACCGGGCTTTGATGCTCTGACACATCCATAGGCTGTCCGGACTGAAACCACGGATCCTCCATCCAGGGCCCCGCCTATTGCGGCTGATTCGACGTAGAAAAGATTATCACCGTAGCTCATGCAGGTTGTTTTGACTGGGTCCTTGAGGGATATTTAATATAAGGATACTGGGAGCAGATATCCTATGTTTGGTGATGAATTGGCTGTTCTATGGGCGCTTTACGGTCCTCCAGTGATTTGCGCTTAAGATACCGC"

rna_string = []
#it would be cooler to add errors at the same frequency as the occur in real transcription
for i in dna_string: 
    if(i == "A"):
        rna_string.append("A")
    if(i == "C"):
        rna_string.append("C")
    if(i == "T"):
        rna_string.append("U")
    if(i == "G"):
        rna_string.append("G")

#weird syntax ... this is bc the join method is of the string class, rather than the list class
#see http://stackoverflow.com/questions/493819/python-join-why-is-it-string-joinlist-instead-of-list-joinstring
print "".join(rna_string)